<a href="https://colab.research.google.com/github/2303A51618/AI-Assistant-Coding/blob/main/AI_ASST_17_3_V.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Create a sample employee dataset
data = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3, 11],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy', 'Charlie', 'Kevin'],
    'salary': [70000, 60000, np.nan, 80000, 75000, 62000, np.nan, 90000, 78000, 65000, 70000, 81000],
    'designation': ['Software Engineer', 'Data Analyst', 'Project Manager', 'Software Engineer', 'HR Manager', 'Data Analyst', np.nan, 'VP', 'Software Engineer', 'Project Manager', 'Project Manager', 'Team Lead'],
    'experience': [5, 3, 8, 6, 4, 2, np.nan, 10, 5, 7, 8, 6],
    'employment_type': ['Full-time', 'Contract', 'Full-time', 'Full-time', 'Part-time', 'Full-time', 'Full-time', 'Full-time', 'Contract', 'Part-time', 'Full-time', 'Full-time']
}
df = pd.DataFrame(data)

print("Original DataFrame:")
display(df)

Original DataFrame:

,employee_id,name,salary,designation,experience,employment_type
0,1,Alice,70000.0,Software Engineer,5.0,Full-time
1,2,Bob,60000.0,Data Analyst,3.0,Contract
2,3,Charlie,NaN,Project Manager,8.0,Full-time
3,4,David,80000.0,Software Engineer,6.0,Full-time
4,5,Eve,75000.0,HR Manager,4.0,Part-time
5,6,Frank,62000.0,Data Analyst,2.0,Full-time
6,7,Grace,NaN,NaN,NaN,Full-time
7,8,Heidi,90000.0,VP,10.0,Full-time
8,9,Ivan,78000.0,Software Engineer,5.0,Contract
9,10,Judy,65000.0,Project Manager,7.0,Part-time
10,3,Charlie,70000.0,Project Manager,8.0,Full-time
11,11,Kevin,81000.0,Team Lead,6.0,Full-time

### 1. Handle Missing Values

- **Salary**: Impute with the median.
- **Designation**: Impute with 'Unknown'.
- **Experience**: Impute with the median.

In [2]:
# Impute missing salary with the median
df['salary'] = df['salary'].fillna(df['salary'].median())

# Impute missing designation with 'Unknown'
df['designation'] = df['designation'].fillna('Unknown')

# Impute missing experience with the median
df['experience'] = df['experience'].fillna(df['experience'].median())

print("DataFrame after handling missing values:")
display(df)

DataFrame after handling missing values:

,employee_id,name,salary,designation,experience,employment_type
0,1,Alice,70000.0,Software Engineer,5.0,Full-time
1,2,Bob,60000.0,Data Analyst,3.0,Contract
2,3,Charlie,72500.0,Project Manager,8.0,Full-time
3,4,David,80000.0,Software Engineer,6.0,Full-time
4,5,Eve,75000.0,HR Manager,4.0,Part-time
5,6,Frank,62000.0,Data Analyst,2.0,Full-time
6,7,Grace,72500.0,Unknown,6.0,Full-time
7,8,Heidi,90000.0,VP,10.0,Full-time
8,9,Ivan,78000.0,Software Engineer,5.0,Contract
9,10,Judy,65000.0,Project Manager,7.0,Part-time
10,3,Charlie,70000.0,Project Manager,8.0,Full-time
11,11,Kevin,81000.0,Team Lead,6.0,Full-time

### 2. Remove Duplicate Employee IDs

We will keep the first occurrence of each `employee_id`.

In [3]:
df.drop_duplicates(subset=['employee_id'], keep='first', inplace=True)

print("DataFrame after removing duplicate employee IDs:")
display(df)

DataFrame after removing duplicate employee IDs:

,employee_id,name,salary,designation,experience,employment_type
0,1,Alice,70000.0,Software Engineer,5.0,Full-time
1,2,Bob,60000.0,Data Analyst,3.0,Contract
2,3,Charlie,72500.0,Project Manager,8.0,Full-time
3,4,David,80000.0,Software Engineer,6.0,Full-time
4,5,Eve,75000.0,HR Manager,4.0,Part-time
5,6,Frank,62000.0,Data Analyst,2.0,Full-time
6,7,Grace,72500.0,Unknown,6.0,Full-time
7,8,Heidi,90000.0,VP,10.0,Full-time
8,9,Ivan,78000.0,Software Engineer,5.0,Contract
9,10,Judy,65000.0,Project Manager,7.0,Part-time
11,11,Kevin,81000.0,Team Lead,6.0,Full-time

### 3. Convert Job Titles to Lowercase

Converting the `designation` column to lowercase for consistency.

In [4]:
df['designation'] = df['designation'].str.lower()

print("DataFrame after converting designations to lowercase:")
display(df)

DataFrame after converting designations to lowercase:

,employee_id,name,salary,designation,experience,employment_type
0,1,Alice,70000.0,software engineer,5.0,Full-time
1,2,Bob,60000.0,data analyst,3.0,Contract
2,3,Charlie,72500.0,project manager,8.0,Full-time
3,4,David,80000.0,software engineer,6.0,Full-time
4,5,Eve,75000.0,hr manager,4.0,Part-time
5,6,Frank,62000.0,data analyst,2.0,Full-time
6,7,Grace,72500.0,unknown,6.0,Full-time
7,8,Heidi,90000.0,vp,10.0,Full-time
8,9,Ivan,78000.0,software engineer,5.0,Contract
9,10,Judy,65000.0,project manager,7.0,Part-time
11,11,Kevin,81000.0,team lead,6.0,Full-time

### 4. Encode Categorical Columns

Using one-hot encoding for `designation` and `employment_type`.

In [5]:
# One-hot encode 'designation' and 'employment_type'
df = pd.get_dummies(df, columns=['designation', 'employment_type'], dtype=int)

print("Cleaned DataFrame after encoding categorical columns:")
display(df)

Cleaned DataFrame after encoding categorical columns:

,employee_id,name,salary,experience,designation_data analyst,designation_hr manager,designation_project manager,designation_software engineer,designation_team lead,designation_unknown,designation_vp,employment_type_Contract,employment_type_Full-time,employment_type_Part-time
0,1,Alice,70000.0,5.0,0,0,0,1,0,0,0,0,1,0
1,2,Bob,60000.0,3.0,1,0,0,0,0,0,0,1,0,0
2,3,Charlie,72500.0,8.0,0,0,1,0,0,0,0,0,1,0
3,4,David,80000.0,6.0,0,0,0,1,0,0,0,0,1,0
4,5,Eve,75000.0,4.0,0,1,0,0,0,0,0,0,0,1
5,6,Frank,62000.0,2.0,1,0,0,0,0,0,0,0,1,0
6,7,Grace,72500.0,6.0,0,0,0,0,0,1,0,0,1,0
7,8,Heidi,90000.0,10.0,0,0,0,0,0,0,1,0,1,0
8,9,Ivan,78000.0,5.0,0,0,0,1,0,0,0,1,0,0
9,10,Judy,65000.0,7.0,0,0,1,0,0,0,0,0,0,1
11,11,Kevin,81000.0,6.0,0,0,0,0,1,0,0,0,1,0

In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Create a sample student dataset
data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
    'name': ['Alex', 'Brian', 'Cathy', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy', 'Liam', 'Mia', 'Noah', 'Olivia', 'Peter'],
    'exam_date': ['2023-09-15', '2023-09-15', '2023-10-20', '2023-10-20', '2023-11-01',
                  '2023-11-01', '2024-02-10', '2024-02-10', '2024-03-05', '2024-03-05',
                  '2023-04-10', '2023-04-10', '2024-01-20', '2024-01-20', '2023-09-15'],
    'subject': ['Math', 'Science', 'Math', 'English', 'Science',
                'English', 'Math', 'Science', 'English', 'Math',
                'Science', 'Math', 'English', 'Science', 'Math'],
    'total_marks': [85, 92, 78, 65, 95, 70, 88, 50, 99, 81, 10, 93, 75, 80, 200]
}
df_students = pd.DataFrame(data)

print("Original Student DataFrame:")
display(df_students)

Original Student DataFrame:

    student_id    name   exam_date  subject  total_marks
0          101    Alex  2023-09-15     Math           85
1          102   Brian  2023-09-15  Science           92
2          103   Cathy  2023-10-20     Math           78
3          104   David  2023-10-20  English           65
4          105     Eve  2023-11-01  Science           95
5          106   Frank  2023-11-01  English           70
6          107   Grace  2024-02-10     Math           88
7          108   Heidi  2024-02-10  Science           50
8          109    Ivan  2024-03-05  English           99
9          110    Judy  2024-03-05     Math           81
10         111    Liam  2023-04-10  Science           10
11         112     Mia  2023-04-10     Math           93
12         113    Noah  2024-01-20  English           75
13         114  Olivia  2024-01-20  Science           80
14         115   Peter  2023-09-15     Math          200

### 1. Convert `exam_date` to Datetime and Extract Features

- Convert the `exam_date` column to datetime objects.
- Extract the month as a number.
- Define a simplified 'semester' based on months (e.g., Spring: Jan-May, Summer: Jun-Aug, Fall: Sep-Dec).
- Extract the day of the month.

In [7]:
# Convert 'exam_date' to datetime objects
df_students['exam_date'] = pd.to_datetime(df_students['exam_date'])

# Extract month
df_students['exam_month'] = df_students['exam_date'].dt.month

# Extract day
df_students['exam_day'] = df_students['exam_date'].dt.day

# Extract semester (simplified)
def get_semester(month):
    if 1 <= month <= 5:
        return 'Spring'
    elif 6 <= month <= 8:
        return 'Summer'
    else:
        return 'Fall'

df_students['exam_semester'] = df_students['exam_month'].apply(get_semester)

print("DataFrame after date conversion and feature extraction:")
display(df_students)

DataFrame after date conversion and feature extraction:

,student_id,name,exam_date,subject,total_marks,exam_month,exam_day,exam_semester
0,101,Alex,2023-09-15,Math,85,9,15,Fall
1,102,Brian,2023-09-15,Science,92,9,15,Fall
2,103,Cathy,2023-10-20,Math,78,10,20,Fall
3,104,David,2023-10-20,English,65,10,20,Fall
4,105,Eve,2023-11-01,Science,95,11,1,Fall
5,106,Frank,2023-11-01,English,70,11,1,Fall
6,107,Grace,2024-02-10,Math,88,2,10,Spring
7,108,Heidi,2024-02-10,Science,50,2,10,Spring
8,109,Ivan,2024-03-05,English,99,3,5,Spring
9,110,Judy,2024-03-05,Math,81,3,5,Spring
10,111,Liam,2023-04-10,Science,10,4,10,Spring
11,112,Mia,2023-04-10,Math,93,4,10,Spring
12,113,Noah,2024-01-20,English,75,1,20,Spring
13,114,Olivia,2024-01-20,Science,80,1,20,Spring
14,115,Peter,2023-09-15,Math,200,9,15,Fall

### 2. Normalize `total_marks`

Using Min-Max scaling to normalize the `total_marks` column to a range between 0 and 1.

In [8]:
# Normalize 'total_marks' using Min-Max Scaling
scaler = MinMaxScaler()
df_students['normalized_marks'] = scaler.fit_transform(df_students[['total_marks']])

print("DataFrame after normalizing 'total_marks':")
display(df_students)

DataFrame after normalizing 'total_marks':

,student_id,name,exam_date,subject,total_marks,exam_month,exam_day,exam_semester,normalized_marks
0,101,Alex,2023-09-15,Math,85,9,15,Fall,0.394737
1,102,Brian,2023-09-15,Science,92,9,15,Fall,0.431579
2,103,Cathy,2023-10-20,Math,78,10,20,Fall,0.357895
3,104,David,2023-10-20,English,65,10,20,Fall,0.289474
4,105,Eve,2023-11-01,Science,95,11,1,Fall,0.447368
5,106,Frank,2023-11-01,English,70,11,1,Fall,0.315789
6,107,Grace,2024-02-10,Math,88,2,10,Spring,0.410526
7,108,Heidi,2024-02-10,Science,50,2,10,Spring,0.210526
8,109,Ivan,2024-03-05,English,99,3,5,Spring,0.468421
9,110,Judy,2024-03-05,Math,81,3,5,Spring,0.373684
10,111,Liam,2023-04-10,Science,10,4,10,Spring,0.000000
11,112,Mia,2023-04-10,Math,93,4,10,Spring,0.436842
12,113,Noah,2024-01-20,English,75,1,20,Spring,0.342105
13,114,Olivia,2024-01-20,Science,80,1,20,Spring,0.368421
14,115,Peter,2023-09-15,Math,200,9,15,Fall,1.000000

### 3. Detect and Remove Outliers from `total_marks` using IQR

We will calculate the Interquartile Range (IQR) for `total_marks` to identify and remove outliers. Outliers are typically defined as data points falling below Q1 - 1.5 * IQR or above Q3 + 1.5 * IQR.

In [9]:
# Calculate Q1 (25th percentile) and Q3 (75th percentile) for 'total_marks'
Q1 = df_students['total_marks'].quantile(0.25)
Q3 = df_students['total_marks'].quantile(0.75)
IQR = Q3 - Q1

# Define upper and lower bounds for outlier detection
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = df_students[(df_students['total_marks'] < lower_bound) | (df_students['total_marks'] > upper_bound)]

print("Identified Outliers in 'total_marks':")
display(outliers)

# Remove outliers from the DataFrame
df_students_cleaned = df_students[~((df_students['total_marks'] < lower_bound) | (df_students['total_marks'] > upper_bound))]

print("\nDataFrame after removing outliers from 'total_marks':")
display(df_students_cleaned)

Identified Outliers in 'total_marks':

,student_id,name,exam_date,subject,total_marks,exam_month,exam_day,exam_semester,normalized_marks
10,111,Liam,2023-04-10,Science,10,4,10,Spring,0.0
14,115,Peter,2023-09-15,Math,200,9,15,Fall,1.0

DataFrame after removing outliers from 'total_marks':

,student_id,name,exam_date,subject,total_marks,exam_month,exam_day,exam_semester,normalized_marks
0,101,Alex,2023-09-15,Math,85,9,15,Fall,0.394737
1,102,Brian,2023-09-15,Science,92,9,15,Fall,0.431579
2,103,Cathy,2023-10-20,Math,78,10,20,Fall,0.357895
3,104,David,2023-10-20,English,65,10,20,Fall,0.289474
4,105,Eve,2023-11-01,Science,95,11,1,Fall,0.447368
5,106,Frank,2023-11-01,English,70,11,1,Fall,0.315789
6,107,Grace,2024-02-10,Math,88,2,10,Spring,0.410526
7,108,Heidi,2024-02-10,Science,50,2,10,Spring,0.210526
8,109,Ivan,2024-03-05,English,99,3,5,Spring,0.468421
9,110,Judy,2024-03-05,Math,81,3,5,Spring,0.373684
11,112,Mia,2023-04-10,Math,93,4,10,Spring,0.436842
12,113,Noah,2024-01-20,English,75,1,20,Spring,0.342105
13,114,Olivia,2024-01-20,Science,80,1,20,Spring,0.368421

In [10]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Create a sample student health dataset
data = {
    'student_id': range(1, 16),
    'age': [16, 17, 16, 18, 17, 16, 18, 17, 16, 18, 17, 16, 18, 17, 16],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male'],
    'height_cm': [170, 165, np.nan, 175, 168, 162, 180, 170, 172, 166, 178, 160, np.nan, 169, 171],
    'weight_kg': [65, 58, 68, np.nan, 60, 55, 75, 62, np.nan, 59, 70, 53, 72, 61, 64],
    'bmi': [22.5, 21.3, 23.5, 22.8, np.nan, 20.9, 23.1, 21.5, 22.0, 21.4, 21.9, np.nan, 23.0, 21.2, 22.3],
    'medical_condition': ['None', 'Asthma', 'None', 'Allergy', np.nan, 'None', 'Asthma', 'None', 'Allergy', 'None', 'None', 'Asthma', 'None', np.nan, 'Allergy'],
    'fitness_status': ['Good', 'Excellent', 'Fair', 'Good', 'Excellent', 'Fair', 'Good', 'Excellent', 'Fair', 'Good', np.nan, 'Fair', 'Good', 'Excellent', 'Good']
}
df_health = pd.DataFrame(data)

print("Original Student Health DataFrame:")
display(df_health)

Original Student Health DataFrame:

,student_id,age,gender,height_cm,weight_kg,bmi,medical_condition,fitness_status
0,1,16,Male,170.0,65.0,22.5,None,Good
1,2,17,Female,165.0,58.0,21.3,Asthma,Excellent
2,3,16,Male,NaN,68.0,23.5,None,Fair
3,4,18,Female,175.0,NaN,22.8,Allergy,Good
4,5,17,Male,168.0,60.0,NaN,NaN,Excellent
5,6,16,Female,162.0,55.0,20.9,None,Fair
6,7,18,Male,180.0,75.0,23.1,Asthma,Good
7,8,17,Female,170.0,62.0,21.5,None,Excellent
8,9,16,Male,172.0,NaN,22.0,Allergy,Fair
9,10,18,Female,166.0,59.0,21.4,None,Good
10,11,17,Male,178.0,70.0,21.9,None,NaN
11,12,16,Female,160.0,53.0,NaN,Asthma,Fair
12,13,18,Male,NaN,72.0,23.0,None,Good
13,14,17,Female,169.0,61.0,21.2,NaN,Excellent
14,15,16,Male,171.0,64.0,22.3,Allergy,Good

### 1. Handle Missing Values

-   **Numerical columns (`height_cm`, `weight_kg`, `bmi`)**: Impute with the median.
-   **Categorical columns (`medical_condition`, `fitness_status`)**: Impute with the mode (most frequent value).

In [11]:
# Impute numerical columns with median
for col in ['height_cm', 'weight_kg', 'bmi']:
    df_health[col] = df_health[col].fillna(df_health[col].median())

# Impute categorical columns with mode
for col in ['medical_condition', 'fitness_status']:
    df_health[col] = df_health[col].fillna(df_health[col].mode()[0])

print("DataFrame after handling missing values:")
display(df_health)

DataFrame after handling missing values:

,student_id,age,gender,height_cm,weight_kg,bmi,medical_condition,fitness_status
0,1,16,Male,170.0,65.0,22.5,None,Good
1,2,17,Female,165.0,58.0,21.3,Asthma,Excellent
2,3,16,Male,170.0,68.0,23.5,None,Fair
3,4,18,Female,175.0,62.0,22.8,Allergy,Good
4,5,17,Male,168.0,60.0,22.0,None,Excellent
5,6,16,Female,162.0,55.0,20.9,None,Fair
6,7,18,Male,180.0,75.0,23.1,Asthma,Good
7,8,17,Female,170.0,62.0,21.5,None,Excellent
8,9,16,Male,172.0,62.0,22.0,Allergy,Fair
9,10,18,Female,166.0,59.0,21.4,None,Good
10,11,17,Male,178.0,70.0,21.9,None,Good
11,12,16,Female,160.0,53.0,22.0,Asthma,Fair
12,13,18,Male,170.0,72.0,23.0,None,Good
13,14,17,Female,169.0,61.0,21.2,None,Excellent
14,15,16,Male,171.0,64.0,22.3,Allergy,Good

### 2. Encode Categorical Columns

Using one-hot encoding for `gender`, `medical_condition`, and `fitness_status`.

In [12]:
# One-hot encode specified categorical columns
df_health_encoded = pd.get_dummies(df_health, columns=['gender', 'medical_condition', 'fitness_status'], dtype=int)

print("DataFrame after encoding categorical columns:")
display(df_health_encoded)

DataFrame after encoding categorical columns:

,student_id,age,height_cm,weight_kg,bmi,gender_Female,gender_Male,medical_condition_Allergy,medical_condition_Asthma,medical_condition_None,fitness_status_Excellent,fitness_status_Fair,fitness_status_Good
0,1,16,170.0,65.0,22.5,0,1,0,0,1,0,0,1
1,2,17,165.0,58.0,21.3,1,0,0,1,0,1,0,0
2,3,16,170.0,68.0,23.5,0,1,0,0,1,0,1,0
3,4,18,175.0,62.0,22.8,1,0,1,0,0,0,0,1
4,5,17,168.0,60.0,22.0,0,1,0,0,1,1,0,0
5,6,16,162.0,55.0,20.9,1,0,0,0,1,0,1,0
6,7,18,180.0,75.0,23.1,0,1,0,1,0,0,0,1
7,8,17,170.0,62.0,21.5,1,0,0,0,1,1,0,0
8,9,16,172.0,62.0,22.0,0,1,1,0,0,0,1,0
9,10,18,166.0,59.0,21.4,1,0,0,0,1,0,0,1
10,11,17,178.0,70.0,21.9,0,1,0,0,1,0,0,1
11,12,16,160.0,53.0,22.0,1,0,0,1,0,0,1,0
12,13,18,170.0,72.0,23.0,0,1,0,0,1,0,0,1
13,14,17,169.0,61.0,21.2,1,0,0,0,1,1,0,0
14,15,16,171.0,64.0,22.3,0,1,1,0,0,0,0,1

### 3. Apply Standard Scaling

Applying `StandardScaler` to numerical features (`age`, `height_cm`, `weight_kg`, `bmi`) to standardize them.

In [13]:
# Identify numerical columns for scaling
numerical_cols = ['age', 'height_cm', 'weight_kg', 'bmi']

# Initialize StandardScaler
scaler = StandardScaler()

# Apply standard scaling
df_health_encoded[numerical_cols] = scaler.fit_transform(df_health_encoded[numerical_cols])

print("DataFrame after applying Standard Scaling:")
display(df_health_encoded)

DataFrame after applying Standard Scaling:

,student_id,age,height_cm,weight_kg,bmi,gender_Female,gender_Male,medical_condition_Allergy,medical_condition_Asthma,medical_condition_None,fitness_status_Excellent,fitness_status_Fair,fitness_status_Good
0,1,-1.075888,0.051451,0.326814,0.547708,0,1,0,0,1,0,0,1
1,2,0.165521,-0.913264,-0.856477,-1.068479,1,0,0,1,0,1,0,0
2,3,-1.075888,0.051451,0.833938,1.894530,0,1,0,0,1,0,1,0
3,4,1.406930,1.016166,-0.180311,0.951755,1,0,1,0,0,0,0,1
4,5,0.165521,-0.334435,-0.518394,-0.125703,0,1,0,0,1,1,0,0
5,6,-1.075888,-1.492093,-1.363602,-1.607208,1,0,0,0,1,0,1,0
6,7,1.406930,1.980881,2.017230,1.355801,0,1,0,1,0,0,0,1
7,8,0.165521,0.051451,-0.180311,-0.799115,1,0,0,0,1,1,0,0
8,9,-1.075888,0.437337,-0.180311,-0.125703,0,1,1,0,0,0,1,0
9,10,1.406930,-0.720321,-0.687436,-0.933797,1,0,0,0,1,0,0,1
10,11,0.165521,1.594995,1.172022,-0.260386,0,1,0,0,1,0,0,1
11,12,-1.075888,-1.877979,-1.701685,-0.125703,1,0,0,1,0,0,1,0
12,13,1.406930,0.051451,1.510105,1.221119,0,1,0,0,1,0,0,1
13,14,0.165521,-0.141492,-0.349353,-1.203161,1,0,0,0,1,1,0,0
14,15,-1.075888,0.244394,0.157772,0.278343,0,1,1,0,0,0,0,1

### 4. Split into Train and Test Sets

Splitting the preprocessed data into training and testing sets (80% train, 20% test).

In [14]:
# For demonstration, let's assume 'age' is our target variable (y) and the rest are features (X)
# In a real scenario, you would choose your target based on the problem you're solving.
X = df_health_encoded.drop(columns=['student_id', 'age']) # Drop student_id and target variable if 'age' is target
y = df_health_encoded['age']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

print("\nFirst 5 rows of X_train:")
display(X_train.head())

Shape of X_train: (12, 11)
Shape of X_test: (3, 11)
Shape of y_train: (12,)
Shape of y_test: (3,)

First 5 rows of X_train:

,height_cm,weight_kg,bmi,gender_Female,gender_Male,medical_condition_Allergy,medical_condition_Asthma,medical_condition_None,fitness_status_Excellent,fitness_status_Fair,fitness_status_Good
13,-0.141492,-0.349353,-1.203161,1,0,0,0,1,1,0,0
5,-1.492093,-1.363602,-1.607208,1,0,0,0,1,0,1,0
8,0.437337,-0.180311,-0.125703,0,1,1,0,0,0,1,0
2,0.051451,0.833938,1.894530,0,1,0,0,1,0,1,0
1,-0.913264,-0.856477,-1.068479,1,0,0,1,0,1,0,0

In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Create a sample ride-sharing dataset
data = {
    'ride_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 101, 111, 112, 113, 114],
    'pickup_location': [' Downtown ', 'airport', 'Suburb A', 'downtown', ' Airport', 'Suburb B', 'downtown', 'airport ', 'Suburb A', 'Downtown', 'Downtown', 'Suburb C', 'Downtown', 'Airport', 'Suburb B'],
    'dropoff_location': ['Airport', 'Downtown', 'Suburb B', 'Airport', 'Suburb A', 'Downtown', 'Suburb B', 'Downtown', 'Airport', 'Suburb C', 'Airport', 'Downtown', 'Suburb A', 'Suburb C', 'Downtown'],
    'distance_km': [10.5, 25.3, 15.0, 11.2, 24.8, 14.5, 12.0, 26.0, 16.0, 18.0, 10.5, 20.0, 13.0, 19.5, 14.5],
    'fare_usd': [20.0, 45.0, 28.0, np.nan, 42.0, 27.0, 22.0, 47.0, np.nan, 35.0, 20.0, 38.0, 25.0, 36.0, 27.0],
    'driver_rating': [4.8, 3.5, 4.9, 4.2, 5.0, 3.0, 4.5, 4.0, 4.7, 3.8, 4.8, 4.6, 4.1, 3.9, 3.0],
    'passenger_count': [1, 2, 1, 1, 3, 2, 1, 1, 2, 1, 1, 2, 1, 2, 2]
}
df_rides = pd.DataFrame(data)

print("Original Ride-Sharing DataFrame:")
display(df_rides)

Original Ride-Sharing DataFrame:

,ride_id,pickup_location,dropoff_location,distance_km,fare_usd,driver_rating,passenger_count
0,101,Downtown,Airport,10.5,20.0,4.8,1
1,102,airport,Downtown,25.3,45.0,3.5,2
2,103,Suburb A,Suburb B,15.0,28.0,4.9,1
3,104,downtown,Airport,11.2,NaN,4.2,1
4,105,Airport,Suburb A,24.8,42.0,5.0,3
5,106,Suburb B,Downtown,14.5,27.0,3.0,2
6,107,downtown,Suburb B,12.0,22.0,4.5,1
7,108,airport,Downtown,26.0,47.0,4.0,1
8,109,Suburb A,Airport,16.0,NaN,4.7,2
9,110,Downtown,Suburb C,18.0,35.0,3.8,1
10,101,Downtown,Airport,10.5,20.0,4.8,1
11,111,Suburb C,Downtown,20.0,38.0,4.6,2
12,112,Downtown,Suburb A,13.0,25.0,4.1,1
13,113,Airport,Suburb C,19.5,36.0,3.9,2
14,114,Suburb B,Downtown,14.5,27.0,3.0,2

### 1. Standardize Pickup/Drop Locations

We will convert the `pickup_location` and `dropoff_location` columns to lowercase and strip leading/trailing whitespace to ensure consistency.

In [16]:
# Standardize location names (lowercase and strip whitespace)
df_rides['pickup_location'] = df_rides['pickup_location'].str.lower().str.strip()
df_rides['dropoff_location'] = df_rides['dropoff_location'].str.lower().str.strip()

print("DataFrame after standardizing locations:")
display(df_rides)

DataFrame after standardizing locations:

,ride_id,pickup_location,dropoff_location,distance_km,fare_usd,driver_rating,passenger_count
0,101,downtown,airport,10.5,20.0,4.8,1
1,102,airport,downtown,25.3,45.0,3.5,2
2,103,suburb a,suburb b,15.0,28.0,4.9,1
3,104,downtown,airport,11.2,NaN,4.2,1
4,105,airport,suburb a,24.8,42.0,5.0,3
5,106,suburb b,downtown,14.5,27.0,3.0,2
6,107,downtown,suburb b,12.0,22.0,4.5,1
7,108,airport,downtown,26.0,47.0,4.0,1
8,109,suburb a,airport,16.0,NaN,4.7,2
9,110,downtown,suburb c,18.0,35.0,3.8,1
10,101,downtown,airport,10.5,20.0,4.8,1
11,111,suburb c,downtown,20.0,38.0,4.6,2
12,112,downtown,suburb a,13.0,25.0,4.1,1
13,113,airport,suburb c,19.5,36.0,3.9,2
14,114,suburb b,downtown,14.5,27.0,3.0,2

### 2. Fill Missing Fare Using Median

Missing values in the `fare_usd` column will be imputed with the median fare to maintain data integrity without skewing the distribution.

In [17]:
# Fill missing 'fare_usd' values with the median
df_rides['fare_usd'] = df_rides['fare_usd'].fillna(df_rides['fare_usd'].median())

print("DataFrame after filling missing fares:")
display(df_rides)

DataFrame after filling missing fares:

,ride_id,pickup_location,dropoff_location,distance_km,fare_usd,driver_rating,passenger_count
0,101,downtown,airport,10.5,20.0,4.8,1
1,102,airport,downtown,25.3,45.0,3.5,2
2,103,suburb a,suburb b,15.0,28.0,4.9,1
3,104,downtown,airport,11.2,28.0,4.2,1
4,105,airport,suburb a,24.8,42.0,5.0,3
5,106,suburb b,downtown,14.5,27.0,3.0,2
6,107,downtown,suburb b,12.0,22.0,4.5,1
7,108,airport,downtown,26.0,47.0,4.0,1
8,109,suburb a,airport,16.0,28.0,4.7,2
9,110,downtown,suburb c,18.0,35.0,3.8,1
10,101,downtown,airport,10.5,20.0,4.8,1
11,111,suburb c,downtown,20.0,38.0,4.6,2
12,112,downtown,suburb a,13.0,25.0,4.1,1
13,113,airport,suburb c,19.5,36.0,3.9,2
14,114,suburb b,downtown,14.5,27.0,3.0,2

### 3. Remove Duplicates

We will identify and remove duplicate rows based on all columns to ensure each ride entry is unique.

In [18]:
# Remove duplicate rows
df_rides.drop_duplicates(inplace=True)

print("DataFrame after removing duplicates:")
display(df_rides)

DataFrame after removing duplicates:

,ride_id,pickup_location,dropoff_location,distance_km,fare_usd,driver_rating,passenger_count
0,101,downtown,airport,10.5,20.0,4.8,1
1,102,airport,downtown,25.3,45.0,3.5,2
2,103,suburb a,suburb b,15.0,28.0,4.9,1
3,104,downtown,airport,11.2,28.0,4.2,1
4,105,airport,suburb a,24.8,42.0,5.0,3
5,106,suburb b,downtown,14.5,27.0,3.0,2
6,107,downtown,suburb b,12.0,22.0,4.5,1
7,108,airport,downtown,26.0,47.0,4.0,1
8,109,suburb a,airport,16.0,28.0,4.7,2
9,110,downtown,suburb c,18.0,35.0,3.8,1
11,111,suburb c,downtown,20.0,38.0,4.6,2
12,112,downtown,suburb a,13.0,25.0,4.1,1
13,113,airport,suburb c,19.5,36.0,3.9,2
14,114,suburb b,downtown,14.5,27.0,3.0,2

### 4. Normalize Driver Ratings

Driver ratings will be normalized using Min-Max Scaling to transform them into a range between 0 and 1. This is useful for algorithms sensitive to the scale of features.

In [19]:
# Normalize 'driver_rating' using Min-Max Scaling
scaler = MinMaxScaler()
df_rides['normalized_driver_rating'] = scaler.fit_transform(df_rides[['driver_rating']])

print("DataFrame after normalizing driver ratings:")
display(df_rides)

DataFrame after normalizing driver ratings:

,ride_id,pickup_location,dropoff_location,distance_km,fare_usd,driver_rating,passenger_count,normalized_driver_rating
0,101,downtown,airport,10.5,20.0,4.8,1,0.90
1,102,airport,downtown,25.3,45.0,3.5,2,0.25
2,103,suburb a,suburb b,15.0,28.0,4.9,1,0.95
3,104,downtown,airport,11.2,28.0,4.2,1,0.60
4,105,airport,suburb a,24.8,42.0,5.0,3,1.00
5,106,suburb b,downtown,14.5,27.0,3.0,2,0.00
6,107,downtown,suburb b,12.0,22.0,4.5,1,0.75
7,108,airport,downtown,26.0,47.0,4.0,1,0.50
8,109,suburb a,airport,16.0,28.0,4.7,2,0.85
9,110,downtown,suburb c,18.0,35.0,3.8,1,0.40
11,111,suburb c,downtown,20.0,38.0,4.6,2,0.80
12,112,downtown,suburb a,13.0,25.0,4.1,1,0.55
13,113,airport,suburb c,19.5,36.0,3.9,2,0.45
14,114,suburb b,downtown,14.5,27.0,3.0,2,0.00

### 5. Summary of Improvements

Let's summarize the changes and improvements made to the dataset:

In [20]:
print("\n--- Cleaning Summary ---")
print("1. Location Standardization: 'pickup_location' and 'dropoff_location' are now consistent (lowercase, no extra spaces).")
print(f"   Example: '{df_rides.iloc[0]['pickup_location']}' instead of original '{data['pickup_location'][0]}'")
print("2. Missing Fare Imputation: Missing 'fare_usd' values were filled using the median.")
print(f"   Number of missing fare values before: {pd.Series(data['fare_usd']).isnull().sum()}")
print(f"   Number of missing fare values after: {df_rides['fare_usd'].isnull().sum()}")
print("3. Duplicate Removal: Duplicate ride entries were removed.")
print(f"   Number of rows before removing duplicates: {len(data['ride_id'])}")
print(f"   Number of rows after removing duplicates: {len(df_rides)}")
print("4. Driver Rating Normalization: A new 'normalized_driver_rating' column was added, scaled between 0 and 1.")
print(f"   Original Driver Rating Range: [{min(data['driver_rating'])} - {max(data['driver_rating'])}]")
print(f"   Normalized Driver Rating Range: [{df_rides['normalized_driver_rating'].min():.2f} - {df_rides['normalized_driver_rating'].max():.2f}]\n")

print("Final Cleaned DataFrame Info:")
df_rides.info()

--- Cleaning Summary ---
1. Location Standardization: 'pickup_location' and 'dropoff_location' are now consistent (lowercase, no extra spaces).
   Example: 'downtown' instead of original ' Downtown '
2. Missing Fare Imputation: Missing 'fare_usd' values were filled using the median.
   Number of missing fare values before: 2
   Number of missing fare values after: 0
3. Duplicate Removal: Duplicate ride entries were removed.
   Number of rows before removing duplicates: 15
   Number of rows after removing duplicates: 14
4. Driver Rating Normalization: A new 'normalized_driver_rating' column was added, scaled between 0 and 1.
   Original Driver Rating Range: [3.0 - 5.0]
   Normalized Driver Rating Range: [0.00 - 1.00]

Final Cleaned DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 14
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ride_id                   14 non-null     int64
 1   pickup_location           14 non-null     object
 2   dropoff_location          14 non-null     object
 3   distance_km               14 non-null     float64
 4   fare_usd                  14 non-null     float64
 5   driver_rating             14 non-null     float64
 6   passenger_count           14 non-null     int64
 7   normalized_driver_rating  14 non-null     float64
dtypes: float64(4), int64(2), object(2)
memory usage: 1008.0+ bytes